language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  - ./travis-tool.sh r_binary_install shiny
  - ./travis-tool.sh r_binary_install testthat
  - ./travis-tool.sh install_github ropensci/RSelenium

script: 
   - R -e 'testthat::test_dir("tests")'

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

